#
# Copyright 2018-2020 Pejman Ghorbanzade. All rights reserved.
#

version: "1.2.1.{build}-{branch}"

image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release

before_build:
  - cmd: cmake -B".\local\build" -H"." -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DWEASEL_BUILD_TESTS=ON -DWEASEL_BUILD_UTILS=ON -DWEASEL_BUILD_EXAMPLES=ON -DWEASEL_BUILD_FRAMEWORK=ON

build:
  project: .\local\build\ALL_BUILD.vcxproj
  parallel: true
  verbosity: normal

after_build:
  - cmd: cmake --install ".\local\build" --prefix ".\local\dist"

test_script:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - cmd: cd "local/build"
  - cmd: ctest . -C Release
